fos_rest:
  routing_loader:
    include_format: false
    default_format: json
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'json' }
  versioning: true
  view:
    view_response_listener: true
  disable_csrf_role: ROLE_API